wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711089296.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.7.10
      5: 0.16.4
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
